-- Inserindo os personagens
INSERT INTO TAB_PERSONAGEM (NOME, CHAKRA, VIDA) VALUES ( 'Naruto Uzumaki', 100, 1000);
INSERT INTO TAB_PERSONAGEM ( NOME, CHAKRA, VIDA) VALUES ( 'Sasuke Uchiha', 100, 950);
INSERT INTO TAB_PERSONAGEM ( NOME, CHAKRA, VIDA) VALUES ( 'Sakura Haruno', 100, 900);
INSERT INTO TAB_PERSONAGEM ( NOME, CHAKRA, VIDA) VALUES ( 'Kakashi Hatake', 100, 1100);
INSERT INTO TAB_PERSONAGEM ( NOME, CHAKRA, VIDA) VALUES ( 'Itachi Uchiha', 100, 1000);

-- Jutsus de Naruto
INSERT INTO PERSONAGEM_JUTSUS (PERSONAGEM_ID, NOME_JUTSU, DANO_MAXIMO) VALUES (1, 'Rasengan', 300);
INSERT INTO PERSONAGEM_JUTSUS (PERSONAGEM_ID, NOME_JUTSU, DANO_MAXIMO) VALUES (1, 'Kage Bunshin no Jutsu', 100);

-- Jutsus de Sasuke
INSERT INTO PERSONAGEM_JUTSUS (PERSONAGEM_ID, NOME_JUTSU, DANO_MAXIMO) VALUES (2, 'Chidori', 350);
INSERT INTO PERSONAGEM_JUTSUS (PERSONAGEM_ID, NOME_JUTSU, DANO_MAXIMO) VALUES (2, 'Amaterasu', 500);

-- Jutsus de Sakura
INSERT INTO PERSONAGEM_JUTSUS (PERSONAGEM_ID, NOME_JUTSU, DANO_MAXIMO) VALUES (3, 'Super Força', 250);
INSERT INTO PERSONAGEM_JUTSUS (PERSONAGEM_ID, NOME_JUTSU, DANO_MAXIMO) VALUES (3, 'Regeneração', 150);

-- Jutsus de Kakashi
INSERT INTO PERSONAGEM_JUTSUS (PERSONAGEM_ID, NOME_JUTSU, DANO_MAXIMO) VALUES (4, 'Raikiri', 400);
INSERT INTO PERSONAGEM_JUTSUS (PERSONAGEM_ID, NOME_JUTSU, DANO_MAXIMO) VALUES (4, 'Kamui', 450);

-- Jutsus de Itachi
INSERT INTO PERSONAGEM_JUTSUS (PERSONAGEM_ID, NOME_JUTSU, DANO_MAXIMO) VALUES (5, 'Tsukuyomi', 500);
INSERT INTO PERSONAGEM_JUTSUS (PERSONAGEM_ID, NOME_JUTSU, DANO_MAXIMO) VALUES (5, 'Amaterasu', 500);
